using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using AISupportAnalysisPlatform.Models.AI;
using AISupportAnalysisPlatform.Constants;

namespace AISupportAnalysisPlatform.Models.AI
{
    public class CopilotChatSession
    {
        public int Id { get; set; }

        public string? UserId { get; set; }
        public ApplicationUser? User { get; set; }

        [Required]
        [MaxLength(200)]
        public string Title { get; set; } = "New Chat";

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime LastInteractionAt { get; set; } = DateTime.UtcNow;

        [MaxLength(50)]
        public string Surface { get; set; } = CopilotSurfaces.Default;

        public bool IsDeleted { get; set; }
        public bool IsAssessment { get; set; }

        public List<CopilotChatMessageEntity> Messages { get; set; } = new();
    }

    public class CopilotChatMessageEntity
    {
        public int Id { get; set; }

        public int SessionId { get; set; }
        public CopilotChatSession? Session { get; set; }

        public ChatMessageRole Role { get; set; }

        [Required]
        public string Content { get; set; } = string.Empty;

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Optional link to a trace history record if this message was generated by the AI
        /// and resulted in a deep investigation.
        /// </summary>
        public int? TraceId { get; set; }
        public CopilotTraceHistory? Trace { get; set; }
    }
}
