namespace SuperAdminCopilot.Retrieval;

using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SuperAdminCopilot.Configuration;

/// <summary>
/// Appends a new entry to <c>verified-queries.json</c> and reloads the read-only
/// store so the matcher picks it up immediately. Companion to <see cref="IVerifiedQueryStore"/>
/// — that interface is intentionally read-only because the matcher's hot path doesn't need
/// write access. The writer is invoked only by the "Promote to Trusted" admin flow.
/// </summary>
public interface IVerifiedQueryWriter
{
    Task<VerifiedQuery> AppendAsync(VerifiedQueryDraft draft, CancellationToken cancellationToken = default);
}

/// <summary>
/// User-supplied fields for a new verified-query entry. Auto-fields (Id, VerifiedAt) are
/// generated by the writer; VerifiedBy defaults to "(promoted via UI)" when blank.
/// </summary>
public sealed record VerifiedQueryDraft(
    string Question,
    string Sql,
    string? Shape = null,
    string? VerifiedBy = null,
    string? Description = null,
    List<string>? QuestionVariants = null,
    List<string>? Tags = null);

internal sealed class VerifiedQueryWriter : IVerifiedQueryWriter
{
    private readonly IOptions<CopilotOptions> _options;
    private readonly IVerifiedQueryStore _store;
    private readonly ILogger<VerifiedQueryWriter> _logger;
    private readonly SemaphoreSlim _gate = new(1, 1);

    public VerifiedQueryWriter(
        IOptions<CopilotOptions> options,
        IVerifiedQueryStore store,
        ILogger<VerifiedQueryWriter> logger)
    {
        _options = options;
        _store = store;
        _logger = logger;
    }

    public async Task<VerifiedQuery> AppendAsync(VerifiedQueryDraft draft, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(draft.Question)) throw new ArgumentException("Question is required.", nameof(draft));
        if (string.IsNullOrWhiteSpace(draft.Sql))      throw new ArgumentException("SQL is required.", nameof(draft));

        await _gate.WaitAsync(cancellationToken);
        try
        {
            var path = ResolvePath(_options.Value.VerifiedQueriesPath);
            if (!File.Exists(path))
                throw new InvalidOperationException($"Verified-queries file not found at '{path}'.");

            var json = await File.ReadAllTextAsync(path, cancellationToken);
            var node = JsonNode.Parse(json)
                ?? throw new InvalidOperationException("verified-queries.json is empty or not valid JSON.");
            var queries = node["queries"]?.AsArray()
                ?? throw new InvalidOperationException("verified-queries.json is malformed — missing 'queries' array.");

            // Reject if the canonical question already exists verbatim. Idempotent
            // promotion — re-clicking Trust on the same answer doesn't double-add.
            var canonical = draft.Question.Trim();
            foreach (var existing in queries)
            {
                var existingQ = existing?["question"]?.GetValue<string>();
                if (string.Equals(existingQ?.Trim(), canonical, StringComparison.OrdinalIgnoreCase))
                {
                    _logger.LogInformation("[VerifiedQueryWriter] Question already exists: '{Q}' — skipping append.", canonical);
                    // Return the existing entry so the caller can still confirm success.
                    return MaterializeFromNode(existing!);
                }
            }

            var id = SlugifyId(canonical);
            var verifiedAt = DateTime.UtcNow.ToString("yyyy-MM-dd");
            var verifiedBy = string.IsNullOrWhiteSpace(draft.VerifiedBy) ? "(promoted via UI)" : draft.VerifiedBy!.Trim();

            var entry = new JsonObject
            {
                ["id"]       = id,
                ["question"] = canonical,
                ["sql"]      = draft.Sql.Trim(),
            };
            if (draft.QuestionVariants is { Count: > 0 })
            {
                var arr = new JsonArray();
                foreach (var v in draft.QuestionVariants)
                    if (!string.IsNullOrWhiteSpace(v)) arr.Add(v.Trim());
                if (arr.Count > 0) entry["questionVariants"] = arr;
            }
            if (!string.IsNullOrWhiteSpace(draft.Shape))       entry["shape"]       = draft.Shape.Trim();
            entry["verifiedAt"]                                = verifiedAt;
            entry["verifiedBy"]                                = verifiedBy;
            if (draft.Tags is { Count: > 0 })
            {
                var arr = new JsonArray();
                foreach (var t in draft.Tags)
                    if (!string.IsNullOrWhiteSpace(t)) arr.Add(t.Trim());
                if (arr.Count > 0) entry["tags"] = arr;
            }
            if (!string.IsNullOrWhiteSpace(draft.Description)) entry["description"] = draft.Description.Trim();

            queries.Add(entry);

            var output = node.ToJsonString(WriterOptions);
            await File.WriteAllTextAsync(path, output, cancellationToken);
            _store.Reload();
            _logger.LogInformation("[VerifiedQueryWriter] Appended '{Id}' to {Path} (now {Count} entries).", id, path, _store.Count);

            return new VerifiedQuery
            {
                Id = id,
                Question = canonical,
                Sql = draft.Sql.Trim(),
                Shape = draft.Shape,
                VerifiedAt = verifiedAt,
                VerifiedBy = verifiedBy,
                Description = draft.Description,
                QuestionVariants = draft.QuestionVariants,
                Tags = draft.Tags,
            };
        }
        finally { _gate.Release(); }
    }

    private static VerifiedQuery MaterializeFromNode(JsonNode node) => new()
    {
        Id       = node["id"]?.GetValue<string>() ?? "",
        Question = node["question"]?.GetValue<string>() ?? "",
        Sql      = node["sql"]?.GetValue<string>() ?? "",
        Shape    = node["shape"]?.GetValue<string>(),
        VerifiedAt = node["verifiedAt"]?.GetValue<string>(),
        VerifiedBy = node["verifiedBy"]?.GetValue<string>(),
    };

    private static string ResolvePath(string path) =>
        Path.IsPathRooted(path) ? path : Path.Combine(Directory.GetCurrentDirectory(), path);

    /// <summary>
    /// Produces a stable, URL-safe id from the question text. ASCII letters/digits only,
    /// hyphenated, max 40 chars, plus a UTC yyyyMMddHHmmss suffix so two near-identical
    /// promotions don't collide on id. Non-Latin scripts (Arabic, etc.) collapse to the
    /// timestamp portion which is fine — the id is opaque, the matcher works on Question.
    /// </summary>
    private static string SlugifyId(string text)
    {
        var slug = (text ?? string.Empty).ToLowerInvariant();
        slug = Regex.Replace(slug, @"[^a-z0-9]+", "-").Trim('-');
        if (slug.Length > 40) slug = slug.Substring(0, 40).TrimEnd('-');
        if (string.IsNullOrEmpty(slug)) slug = "promoted";
        return $"{slug}-{DateTime.UtcNow:yyyyMMddHHmmss}";
    }

    private static readonly JsonSerializerOptions WriterOptions = new()
    {
        WriteIndented = true,
        // Don't escape Arabic / CJK / other non-ASCII — preserves human-readable
        // QuestionVariants in the JSON file.
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };
}
