namespace SuperAdminCopilot.Schema;

using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SuperAdminCopilot.Configuration;
using SuperAdminCopilot.Models;

/// <summary>
/// Runtime schema-knowledge service. Reads <c>schema-inferred.json</c> (generated by the
/// Layer-2 inference job) and merges in the human-curated <c>schema-overrides.json</c>.
/// Exposed to retrievers, the spec extractor, and the compiler as the single source of truth
/// for "what does the copilot know about the database."
///
/// Threading: snapshot-style — <see cref="Reload"/> swaps the cached state atomically. Readers
/// see a consistent merged view; writers (the inference UI) call Reload() after regenerating.
/// </summary>
public interface ISchemaKnowledge
{
    /// <summary>True when the inferred file exists and was parsed successfully.</summary>
    bool IsAvailable { get; }
    DateTimeOffset? LoadedAt { get; }
    string? SchemaHash { get; }
    int TableCount { get; }
    InferredTable? GetTable(string tableName);
    IReadOnlyList<InferredTable> AllTables { get; }
    /// <summary>Force re-read from disk. Call after the inference job regenerates the file.</summary>
    void Reload();
}

internal sealed class SchemaKnowledge : ISchemaKnowledge
{
    private readonly IOptions<CopilotOptions> _options;
    private readonly ILogger<SchemaKnowledge> _logger;
    private readonly object _gate = new();
    private SchemaKnowledgeSnapshot _snapshot = SchemaKnowledgeSnapshot.Empty;

    public SchemaKnowledge(IOptions<CopilotOptions> options, ILogger<SchemaKnowledge> logger)
    {
        _options = options;
        _logger = logger;
        TryLoad();
    }

    public bool IsAvailable => _snapshot.IsAvailable;
    public DateTimeOffset? LoadedAt => _snapshot.LoadedAt;
    public string? SchemaHash => _snapshot.SchemaHash;
    public int TableCount => _snapshot.Tables.Count;
    public IReadOnlyList<InferredTable> AllTables => _snapshot.Tables;

    public InferredTable? GetTable(string tableName)
    {
        if (string.IsNullOrEmpty(tableName)) return null;
        return _snapshot.TablesByName.TryGetValue(tableName, out var t) ? t : null;
    }

    public void Reload()
    {
        lock (_gate) { TryLoad(); }
    }

    private void TryLoad()
    {
        var opts = _options.Value;
        var inferredPath = ResolvePath(opts.SchemaInferredPath);
        var overridesPath = ResolvePath(opts.SchemaOverridesPath);

        if (!File.Exists(inferredPath))
        {
            _logger.LogWarning(
                "[SuperAdminCopilot] Schema knowledge: inferred file missing at {Path}. " +
                "Generate it via Copilot Settings → Schema Knowledge → Generate.", inferredPath);
            _snapshot = SchemaKnowledgeSnapshot.Empty;
            return;
        }

        try
        {
            var inferred = JsonSerializer.Deserialize<SchemaInferenceResult>(
                File.ReadAllText(inferredPath), DeserializerOptions);
            if (inferred is null)
            {
                _logger.LogWarning("[SuperAdminCopilot] Schema knowledge: inferred file deserialized to null.");
                _snapshot = SchemaKnowledgeSnapshot.Empty;
                return;
            }

            SchemaOverrides? overrides = null;
            if (File.Exists(overridesPath))
            {
                try
                {
                    overrides = JsonSerializer.Deserialize<SchemaOverrides>(
                        File.ReadAllText(overridesPath), DeserializerOptions);
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex,
                        "[SuperAdminCopilot] Schema knowledge: overrides file at {Path} failed to parse — ignored.",
                        overridesPath);
                }
            }

            // Warn about overrides that reference tables / columns absent from the inferred file.
            // These usually indicate a typo or stale override after a schema change.
            if (overrides?.Tables is { Count: > 0 })
            {
                var knownTables = inferred.Tables.ToDictionary(t => t.Name, StringComparer.OrdinalIgnoreCase);
                foreach (var ov in overrides.Tables)
                {
                    if (!knownTables.TryGetValue(ov.Name, out var infTable))
                    {
                        _logger.LogWarning("[SuperAdminCopilot] Schema overrides: table '{Table}' is not in the inferred file. Override ignored.", ov.Name);
                        continue;
                    }
                    if (ov.Columns is { Count: > 0 })
                    {
                        foreach (var c in ov.Columns)
                        {
                            if (!infTable.Columns.Any(ic => string.Equals(ic.Name, c.Name, StringComparison.OrdinalIgnoreCase)))
                                _logger.LogWarning("[SuperAdminCopilot] Schema overrides: column '{Table}.{Column}' is not in the inferred file. Override ignored.", ov.Name, c.Name);
                        }
                    }
                }
            }

            var merged = MergeOverrides(inferred.Tables, overrides?.Tables ?? new List<TableOverride>());
            var byName = merged.ToDictionary(t => t.Name, StringComparer.OrdinalIgnoreCase);

            _snapshot = new SchemaKnowledgeSnapshot
            {
                IsAvailable = true,
                LoadedAt = DateTimeOffset.UtcNow,
                SchemaHash = inferred.SchemaHash,
                Tables = merged,
                TablesByName = byName,
            };

            _logger.LogInformation(
                "[SuperAdminCopilot] Schema knowledge loaded: {Tables} tables (overrides: {OverrideCount}).",
                merged.Count, overrides?.Tables?.Count ?? 0);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[SuperAdminCopilot] Schema knowledge: load failed.");
            _snapshot = SchemaKnowledgeSnapshot.Empty;
        }
    }

    // ── Merge logic ───────────────────────────────────────────────────────────────────
    // Override file is sparse — only fields present in the override replace the inferred value.
    // Columns are merged by name (case-insensitive). Adding entirely new columns / tables via
    // overrides is supported but discouraged (the generated file should be the ground truth).
    // Table / column existence validation lives inline in TryLoad above.

    private static List<InferredTable> MergeOverrides(
        List<InferredTable> inferred, IReadOnlyList<TableOverride> overrides)
    {
        if (overrides.Count == 0) return inferred;
        var overrideMap = overrides.ToDictionary(o => o.Name, StringComparer.OrdinalIgnoreCase);
        var merged = new List<InferredTable>(inferred.Count);

        foreach (var t in inferred)
        {
            if (!overrideMap.TryGetValue(t.Name, out var ov))
            {
                merged.Add(t);
                continue;
            }
            merged.Add(ApplyOverride(t, ov));
        }
        return merged;
    }

    private static InferredTable ApplyOverride(InferredTable t, TableOverride ov)
    {
        var roles = new InferredRoles
        {
            LabelColumn = ov.Roles?.LabelColumn ?? t.Roles.LabelColumn,
            SoftDeleteColumn = ov.Roles?.SoftDeleteColumn ?? t.Roles.SoftDeleteColumn,
            NaturalKey = ov.Roles?.NaturalKey ?? t.Roles.NaturalKey,
        };
        var flags = new InferredFlags
        {
            IsBridge = ov.Flags?.IsBridge ?? t.Flags.IsBridge,
            IsLookup = ov.Flags?.IsLookup ?? t.Flags.IsLookup,
            IsPerson = ov.Flags?.IsPerson ?? t.Flags.IsPerson,
        };
        var cols = ApplyColumnOverrides(t.Columns, ov.Columns ?? new List<ColumnOverride>());

        // Merge synonyms: auto + overrides (deduplicated, case-insensitive). The override
        // is *additive*, not replacing — Arabic forms come from overrides without erasing
        // the auto-generated English forms.
        var mergedSynonyms = new List<string>(t.Synonyms);
        if (ov.Synonyms is { Count: > 0 })
        {
            var seen = new HashSet<string>(mergedSynonyms, StringComparer.OrdinalIgnoreCase);
            foreach (var s in ov.Synonyms)
                if (!string.IsNullOrWhiteSpace(s) && seen.Add(s)) mergedSynonyms.Add(s);
        }

        return new InferredTable
        {
            Name = t.Name,
            Schema = t.Schema,
            Description = ov.Description ?? t.Description,
            PrimaryKey = t.PrimaryKey,
            Flags = flags,
            Roles = roles,
            Columns = cols,
            ForeignKeysOut = t.ForeignKeysOut,
            ReferencedBy = t.ReferencedBy,
            SampleValues = t.SampleValues,
            Synonyms = mergedSynonyms,
            Source = ov.HasAnyValue() ? SpecConstants.InferenceSources.HeuristicPlusOverride : t.Source,
        };
    }

    private static List<InferredColumn> ApplyColumnOverrides(
        List<InferredColumn> cols, IReadOnlyList<ColumnOverride> overrides)
    {
        if (overrides.Count == 0) return cols;
        var ovMap = overrides.ToDictionary(o => o.Name, StringComparer.OrdinalIgnoreCase);
        var merged = new List<InferredColumn>(cols.Count);
        foreach (var c in cols)
        {
            if (!ovMap.TryGetValue(c.Name, out var cov))
            {
                merged.Add(c);
                continue;
            }
            merged.Add(new InferredColumn
            {
                Name = c.Name,
                Type = c.Type,
                Nullable = c.Nullable,
                Role = cov.Role ?? c.Role,
                DateRole = cov.DateRole ?? c.DateRole,
                FkRole = cov.FkRole ?? c.FkRole,
                References = cov.References ?? c.References,
                IsPii = cov.IsPii ?? c.IsPii,
                Description = cov.Description ?? c.Description,
                Synonyms = cov.Synonyms ?? c.Synonyms,
                SampleValues = cov.SampleValues ?? c.SampleValues,
            });
        }
        return merged;
    }

    private static string ResolvePath(string path) =>
        Path.IsPathRooted(path) ? path : Path.Combine(Directory.GetCurrentDirectory(), path);

    private static readonly JsonSerializerOptions DeserializerOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        AllowTrailingCommas = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
    };

    private sealed class SchemaKnowledgeSnapshot
    {
        public bool IsAvailable { get; init; }
        public DateTimeOffset? LoadedAt { get; init; }
        public string? SchemaHash { get; init; }
        public List<InferredTable> Tables { get; init; } = new();
        public Dictionary<string, InferredTable> TablesByName { get; init; } = new(StringComparer.OrdinalIgnoreCase);

        public static readonly SchemaKnowledgeSnapshot Empty = new();
    }
}

// Override models (SchemaOverrides, TableOverride, etc.) live in SchemaInferenceModels.cs.
